version: "3"

services:
  web:
    build: './web'
    container_name: web-strapi-demo
    restart: unless-stopped
    ports:
      - 3000:80
    depends_on:
      - "strapi"

  strapi:
    image: strapi/strapi
    container_name: srv-strapi-demo
    volumes:
      - ./strapi:/srv/app
    ports:
      - '1337:1337'

volumes:
  strapidata: